# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5de877f3be94a665a2fe8400fcf433238b879214bd272d04e2587702e7dcdcdfefa820c2ba1f0f1816831401246bacbd5a79ce242bac0fd680d739a6a824beb6

test:
  secret_key_base: cc871540dc766b0344381b5f377957b54f922f3160c136dc04ad56e3f37319ceab3fcdb15bea57cb29e669662e6487251c9b775d6b0475fe5c2127f9795ba74d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
